//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace forum
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeRatings
    {
        public int RatingID { get; set; }
        public int RecipeID { get; set; }
        public int UserID { get; set; }
        public int RatingValue { get; set; }
        public Nullable<System.DateTime> RatingDate { get; set; }
    
        public virtual Recipes Recipes { get; set; }
        public virtual Users Users { get; set; }
    }
}
